### PR TITLE
Android Activities

### PR DESCRIPTION
**Pull request by vincekruger**
I've updated the android activity monitor to include more of the error messages from the stickers module.

### CODE REVIEW

**Comment by kesepara** [comment]
@vincekruger did you manage to add this plugin to iOS ?

**Comment by vincekruger** [comment]
Yup.  I added it manually, but I haven't done any further integration with iOS just yet.

**Comment by kesepara** [comment]
@vincekruger okay. i couldn't do that. error happens every time. can you please let me know if you can do the integrations?

**Comment by vincekruger** [comment]
> @vincekruger okay. i couldn't do that. error happens every time. can you please let me know if you can do the integrations?

What errors are you getting?

**Comment by vincekruger** [comment]
The problem is not the stickers project.  iOS doesn't support WebP out the box.  Here is a great article explaining all of this and how to add support for WebP to iOS

https://medium.com/@tgpski/react-native-webp-reducing-bundle-binary-sizes-increase-speed-with-webp-image-format-aa9b1aa11405

**Comment by Jobeso** [comment]
Great PR, very valuable! I look into it and merge it then.

Probably it makes sense to add an example project to the repo for easier testing in the future.

**Comment by vincekruger** [comment]
@Jobeso I can do the android one if you do the iOS one. ;)

**Comment by Jobeso** [comment]
> @Jobeso I can do the android one if you do the iOS one. ;)

Sounds good :)

**Comment by Jobeso** [comment]
@kesepara Like @vincekruger  mentioned the WebP framework integration is probably the problem here. There is a section in the integration part of the `README` about WebP integration. Hope that helps, otherwise feel free to open an issue to get help.

**Comment by kesepara** [comment]
> @kesepara Like @vincekruger mentioned the WebP framework integration is probably the problem here. There is a section in the integration part of the `README` about WebP integration. Hope that helps, otherwise feel free to open an issue to get help.

Thanks both of you guys @vincekruger @Jobeso . I am going to try these solutions right now.

**Comment by Jobeso** [comment]
Hey @vincekruger,
I finally found the time to test this and look over it. It looks really good and I think it is a great enhancement.
Please pull the master and then I can merge this PR. Please make sure you accept the version from master in the package.json.
Thanks

**Pull request closed without merging**
